services:
  server:
    build:
      context: ./
      dockerfile: src/server/Dockerfile
    ports:
      - "5005:5005"
    environment:
      - NODE_ENV=production
      - DB_HOST=database
      - DB_USER=blest
      - DB_NAME=pokedex
      - DB_PORT=5432
      - SESSION_SECRET=secret
    depends_on:
      - database
    networks:
      - app-network

  client:
    build:
      context: ./
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - app-network

  database:
    image: postgres:14
    environment:
      - POSTGRES_USER=blest
      - POSTGRES_DB=pokedex
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:


networks:
  app-network:
