services:
  server:
    build:
      context: ./
      dockerfile: src/server/Dockerfile
    ports:
      - "5005:5005"
    environment:
      - NODE_ENV=production
      - SESSION_SECRET=secret
      - DB_HOST=database
      - DB_NAME=pokedex
      - DB_PORT=5432
      - DB_USER=blest
      - DB_PASSWORD=trickmac
    depends_on:
      - database
    volumes:
      - ./src/server:/app/src/server
      - ./wait-for-it.sh:/wait-for-it.sh # Mount wait-for-it script
    networks:
      - app-network
    # command: [ "sh", "-c", "echo DB_PASSWORD=$DB_PASSWORD && node src/server/server.js" ]

  client:
    build:
      context: ./
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - app-network

  database:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=blest
      - POSTGRES_DB=pokedex
      - POSTGRES_PASSWORD=trickmac
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    # command: [ "sh", "-c", "echo POSTGRES_PASSWORD=$POSTGRES_PASSWORD && docker-entrypoint.sh postgres" ]



networks:
  app-network:
